CREATE TABLE [Room](
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
    [SupportedStudents] TINYINT NOT NULL DEFAULT(30),
    [Code] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PK_Room_Id] PRIMARY KEY([Id])
)



